name: Build library
on: [push]
jobs:
  build-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure build
        run: cmake -Bbuild -H$GITHUB_WORKSPACE

      - name: Build library
        run: cd build && make all
      
      - name: Install Library
        run: cd build && make DESTDIR=install install
